version: '3.8'

services:
  goprojectgen:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goprojectgen
    restart: unless-stopped
    environment:
      - TZ=UTC
    volumes:
      - .:/app  # Mount the current directory to /app in the container
      - ${PWD}:/output  # Mount the current directory to /output for writing generated projects
    working_dir: /app
    stdin_open: true  # Keeps STDIN open for interactive CLI
    tty: true  # Allocates a pseudo-TTY for interactive CLI